[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install fastapi uvicorn"]

[phases.build]
cmds = ["echo 'No build needed - dependencies installed'"]

[start]
cmd = "python3 main.py"
