name: CI & Publish

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6

      - name: Install dev deps
        run: uv sync --all-extras --dev

      - name: Ruff / MyPy / PyTest
        run: |
          uv run ruff check .
          uv run mypy src
          uv run pytest --cov=src/caltrain_mcp --cov-report=term-missing

      - name: Python Semantic Release
        id: semrel
        uses: python-semantic-release/python-semantic-release@v9.21.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: 'github-actions'
          git_committer_email: 'actions@users.noreply.github.com'

      - name: Checkout tagged version for building
        if: steps.semrel.outputs.released == 'true'
        uses: actions/checkout@v4
        with:
          ref: v${{ steps.semrel.outputs.version }}
          clean: true

      - name: Setup Python for build
        if: steps.semrel.outputs.released == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv for build
        if: steps.semrel.outputs.released == 'true'
        uses: astral-sh/setup-uv@v6

      - name: Build package from clean tag
        if: steps.semrel.outputs.released == 'true'
        run: |
          # Verify we're on the right tag
          echo "Current git describe: $(git describe --exact-match --tags HEAD)"
          echo "Git status: $(git status --porcelain)"

          # Install build dependencies
          uv sync --dev

          # Build the package
          uv run python -m build

          # Show what was built
          ls -la dist/

      - name: Publish to PyPI
        if: steps.semrel.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
