name: CI & Publish

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6

      - name: Install dev deps
        run: uv sync --all-extras --dev

      - name: Ruff / MyPy / PyTest
        run: |
          uv run ruff check .
          uv run mypy src
          uv run pytest --cov=src/caltrain_mcp --cov-report=term-missing

      - name: Build package
        run: uv run python -m build

      - name: Python Semantic Release
        id: semrel
        uses: python-semantic-release/python-semantic-release@v9.21.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: 'github-actions'
          git_committer_email: 'actions@users.noreply.github.com'

      - name: Publish to PyPI
        if: steps.semrel.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
